version: '3.8'

services:
  devdb:
    image: postgres:13
    container_name: postgres-dev
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  testdb:
    image: postgres:13
    container_name: postgres-test
    ports:
      - "5432:5432"
    env_file:
      - .env.int.test

volumes:
  pgdata: