name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci --prefix apps/front
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --cwd apps/front
      - name: Run Playwright tests
        run: npx playwright test --cwd apps/front
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/front/playwright-report/
          retention-days: 30
